Front relay
Robuske/sisop2-t1 pull request #22
Opened 2020-11-06 23:03 UTC by hvsw

2020-11-16 13:07 UTC, hvsw commented
1. `./client henrique grupo localhost 30000`
2. `./client henrique2 grupo localhost 30000`
3. Ao logar com o `henrique2`, o front está enviando uma mensagem pro client errado.

<img width="1495" alt="Screen Shot 2020-11-16 at 09 58 05" src="https://user-images.githubusercontent.com/2053643/99255987-76e22380-27f3-11eb-914c-1bc6612d0038.png">

2020-11-17 08:31 UTC, Robuske requested changes

2020-11-17 08:31 UTC, Robuske commented on front/sources/FrontCommunicationManager.cpp
> +int FrontCommunicationManager::sendPacketToServerSocket(Packet packet, SocketFD socket) {
```suggestion
int FrontCommunicationManager::sendPacketToSocket(Packet packet, SocketFD socket) {
```

2020-11-17 08:31 UTC, Robuske commented on front/sources/FrontCommunicationManager.cpp
> +}
**Acho que ta aqui o problema.**
Tu só tem um socket pro server, e como o `CommunicationsManager` do server baseia tudo que ele faz no socket de conexão ele acha que é tudo o mesmo client, algumas coisas funcionam porque usamos o nome/grupo que vão na mensagem. Até me surpreende o quanto funciona, tu tem múltiplas threads lendo do mesmo socket (o do server), a primeira que lê é a que faz algo, possivelmente as vezes até mais de uma lê ao mesmo tempo.

Acho que a solução mais "simples" que consigo imaginar é o front ter uma só thread de leitura do server que encaminha para o client correto.
Pra saber qual o client correto (tanto no front quanto no server) vamos ter que adicionar no `Packet` o socket de conexão do front com o client e um id pro front (pra quando tiver múltiplos fronts o server não cair no mesmo problema de novo).
Como falei num outro comentário, o server que conecta no front não o contrário, então já vamos precisar de "ids" pros fronts saberem qual ip/porta usarem do arquivo de config, ou seja, vai ter uma lista de ip/porta num arquivo, como cada front sabe qual deles usarem pra deixar aberto pro server? O front vai precisar receber esse id como parâmetro de inicialização ou pedir o input.
(os servers vão precisar do mesmo esquema pra se identificar entre eles)

Como o client cria um `Packet` do lado dele, ele vai precisar por um `-1`  ou algo do tipo, aí o front configura o valor quando for enviar pro server.

2020-11-21 17:12 UTC, merged