Server connections
Robuske/sisop2-t1 pull request #25
Opened 2020-11-21 21:33 UTC by douglasgeh

### What 

* In this branch we've implemented the ring election algorithm.

### Why 

* When managing replicas an election should start each time the coordinator server disconnects.
* After the election end a backup server will take the place of the coordinator

2020-11-21 22:21 UTC, hvsw requested changes
Tá bonito! 🚀

2020-11-21 22:21 UTC, hvsw commented on shared/sources/SharedDefinitions.h
> +//typedef std::map<int , SocketConnectionInfo> AvailableConnections;
```suggestion
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/main.cpp
> +    int serverID = 100;
Como vamos gerar o server ID?

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.h
> + */
Se o server vai dar start na election então melhor chamar de `startElection()`, não?
```suggestion
/** Each time a server start a new election
 * it needs to call startElection() and then
 * send a message with its id to the current
 * connected server using the electionConnnection
 * socket
 */
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +//}
```suggestion
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/CommunicationManager/ServerCommunicationManager.h
> +    void setupBackup();
```suggestion
    void startTestElection();
    void setupMainConnection();
    void setupBackup();
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/CommunicationManager/ServerCommunicationManager.cpp
> +        // Não estamos usando o id da thread depois, só estamos passando um valor porque usar nullptr no primeiro parâmetro da um warning
Qual id da thread?

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    serverConfigFile[4] = fifthConnection;
Temos que fazer o serviço de descoberta. `servers.conf` talvez?

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    int numberOfConnections =  sizeof(serverConfigFile)/sizeof(AvailableConnection);
Isso provavelmente vai mudar, mas tá correto? `sizeof(serverConfigFile)` vai retornar 5 ou 5 * `sizeof(AvailableConnection)`?

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    this->elected = -1;
Criar uma constante pro -1 que adicione valor semântico. Isso é `NONE_ELECTED`, `ELECTION_RUNNING` ou algo assim?
```suggestion
    this->elected = NONE_ELECTED;
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    if(this->elected == this->serverID) {
```suggestion
    if (this->elected == this->serverID) {
```

2020-11-21 22:21 UTC, hvsw commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    return Message(TypeElection, now(), clientNotSet, clientNotSet,"", "",std::to_string(this->serverID));
```suggestion
    return Message(TypeElection, now(), clientNotSet, clientNotSet, "", "", std::to_string(this->serverID));
```

2020-11-23 00:43 UTC, Robuske commented on server/sources/main.cpp
> +    int serverID = 100;
parâmetro de inicialização, junto com o loadMessagesCount

2020-11-23 00:45 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    serverConfigFile[4] = fifthConnection;
Serviço de descoberta? Quer dizer leitura de um arquivo? Acho que não vale o esforço, melhor deixar como um array assim, teríamos que ou fazer um parse tri chato do texto ou então criar um negócio que gera o arquivo de config com os bytes corretos pra poder já ler direto

2020-11-23 05:14 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +}
Não usou isso no fim das contas

2020-11-23 05:14 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +}
Também não usou

2020-11-23 05:14 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.h
> +
```suggestion
```

2020-11-23 05:14 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.h
> + */
Acho que a ideia é que ele tem que configurar várias coisas, por isso `setup`, `start` seria quem chama o `setup` talvez =P
Mas acho que tanto faz

2020-11-23 05:14 UTC, Robuske commented on shared/sources/SharedDefinitions.h
> +//typedef std::map<int , SocketConnectionInfo> AvailableConnections;
Acho que teria que apagar toda a documentação ali de cima também no caso.

2020-11-23 11:19 UTC, hvsw commented on shared/sources/SharedDefinitions.h
> +//typedef std::map<int , SocketConnectionInfo> AvailableConnections;
Possivelmente. @douglasgeh up to u

2020-11-23 18:18 UTC, douglasgeh commented on server/sources/main.cpp
> +
Temos que descomentar isso na vdd para pegar os parâmetros pela linha de comando.

2020-11-23 18:19 UTC, douglasgeh commented on shared/sources/SharedDefinitions.h
> +//typedef std::map<int , SocketConnectionInfo> AvailableConnections;
Yes

2020-11-23 18:20 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    int numberOfConnections =  sizeof(serverConfigFile)/sizeof(AvailableConnection);
sizeof(serverConfigFile) vai retornar 5 * sizeof(AvailableConnection), posso mudar pra um array do C++ então, embora nao sei se precisa.

2020-11-23 18:20 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    this->elected = -1;
Boa

2020-11-23 18:25 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +//}
Feito

2020-11-23 18:25 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    serverConfigFile[4] = fifthConnection;
Beleza! Vou deixar assim então por enquanto.

2020-11-23 18:29 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    this->elected = -1;
Criei ELECTION_RUNNING

2020-11-23 18:33 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    if(this->elected == this->serverID) {
Feito

2020-11-23 18:33 UTC, douglasgeh commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    return Message(TypeElection, now(), clientNotSet, clientNotSet,"", "",std::to_string(this->serverID));
Feito

2020-11-23 18:34 UTC, Robuske commented on server/sources/ElectionManager/ServerElectionManager.cpp
> +    int numberOfConnections =  sizeof(serverConfigFile)/sizeof(AvailableConnection);
Ah verdade, esqueci que não é um array do C++, mas já que tu ta pondo um tamanho hardcoded, porque não põe num define e utiliza nos dois lugares logo?

2020-11-23 18:34 UTC, douglasgeh commented on server/CMakeLists.txt
> +add_executable(server sources/main.cpp sources/ElectionManager/ServerElectionManager.cpp sources/ElectionManager/ServerElectionManager.h)
Ops kkkk sorry depois podemos ver se mudamos ou não

2020-11-23 18:36 UTC, douglasgeh commented on server/sources/CommunicationManager/ServerCommunicationManager.cpp
> +void ServerCommunicationManager::startTestElection() {
Podemos renomear e refletir o uso dela pq vamos precisar de uma função pra iniciar a eleição da mesma forma

2020-11-23 18:37 UTC, douglasgeh commented on server/sources/CommunicationManager/ServerCommunicationManager.cpp
> +void ServerCommunicationManager::setupBackup() {
Beleza

2020-11-23 18:37 UTC, douglasgeh commented on server/sources/CommunicationManager/ServerCommunicationManager.cpp
> +void ServerCommunicationManager::startTestElection() {
Renomeei para startElection apenas depois podemos mudar

2020-11-23 18:38 UTC, douglasgeh commented on server/sources/CommunicationManager/ServerCommunicationManager.cpp
> +   while(true);
Feito

2020-11-23 21:39 UTC, hvsw reviewed
Ficou pendurado os comentários. Segue novo review :3

2020-11-23 21:41 UTC, merged